version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: admission_db
    environment:
      # This pulls the values directly from your .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend-folder
    container_name: admission_portal_backend
    env_file: .env # This loads your Groq Key and DB URL into the backend
    ports:
      - "8001:8001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: admission_portal_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: